export const projectsData = [
  //   {
  //     name: "Chatnet",
  //     imgSrc: "/projects/chatnet.jpg",
  //     dates: "04 / 2023 - Present",
  //     desc: "A real time chat application built with Next 13's app directory /react server components",
  //     techList: ["TypeScript", "NextJS", "TailwindCSS", "Redis"],
  //     demoUrl: "https://chatnet.vercel.app",
  //     codeUrl: "https://github.com/mathewbushuru/chatnet",
  //   },
  {
    name: "UI / Component library ",
    imgSrc: "/mockups/ipad/component_library_ipad.png",
    dates: "04 / 2023 - Present",
    desc: "A collection of prebuilt UI elements that I usually need in new projects. For example navbars, footers, cards, etc.",
    techList: ["TypeScript", "NextJS", "TailwindCSS"],
    demoUrl: "https://matt-components.vercel.app/",
    codeUrl: "https://github.com/mathewbushuru/component-library",
  },
  {
    name: "Soma's vision ",
    imgSrc: "/mockups/ipad/soma_org_ipad.png",
    dates: "04 / 2023 - Present",
    desc: "A complete redesign of Soma's landing page to represent my vision of Soma's future.",
    techList: ["JavaScript", "ReactJS", "CSS"],
    demoUrl: "https://www.somaoffline.org/",
    codeUrl: null,
  },
  {
    name: "ProSearchX",
    imgSrc: "/mockups/ipad/prosearchx_ipad.png",
    dates: "03 / 2023 ",
    desc: "A  wrapper around Google Search with additional features to make it more effective and powerful.",
    techList: ["JavaScript", "ReactJS", "CSS"],
    demoUrl: "https://pro-search-x.vercel.app/",
    codeUrl: "https://github.com/mathewbushuru/ProSearchX",
  },
  {
    name: "Unbeatable TicTacToe",
    imgSrc: "/mockups/ipad/unbeatable_tictactoe_ipad.png",
    dates: "03 / 2023 ",
    desc: "A vanilla JS project utilizing the module pattern and the minmax algorithm to create an unbeatable TicTacToe bot.",
    techList: ["JavaScript", "CSS"],
    demoUrl: "https://mathewbushuru.github.io/unbeatable-tictactoe/",
    codeUrl: "https://github.com/mathewbushuru/unbeatable-tictactoe",
  },
  {
    name: "Google Search Clone",
    imgSrc: "/mockups/ipad/google_ipad.png",
    dates: "02 / 2023 ",
    desc: "A clone of Google Search with real time search results using Custom Search Engine (CSE).",
    techList: ["JavaScript", "ReactJS", "CSS"],
    demoUrl: "https://googly-lovat.vercel.app/",
    codeUrl: "https://github.com/mathewbushuru/googly",
  },
  {
    name: "Previous Portfolio",
    imgSrc: "/mockups/ipad/oldportfolio_ipad.png",
    dates: "02 / 2022 ",
    desc: "My dark-themed portfolio with a feature to open live project demos from a lightbox / modal within the app.",
    techList: ["JavaScript", "HTML", "CSS", "Bootstrap"],
    demoUrl: "https://mathewbushuru.me/",
    codeUrl: null,
  },
  {
    name: "Soma",
    imgSrc: "/mockups/ipad/somaoriginal_ipad.png",
    dates: "07 / 2019 ",
    desc: "Soma's landing page.",
    techList: ["JavaScript", "HTML", "CSS", "Bootstrap"],
    demoUrl: "https://www.somaoffline.com/",
    codeUrl: null,
  },
];
