name: Continuous Integration
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
jobs:
  all-cli-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "20.10"
      - run: yarn install
      - run: yarn  build
      # - run: yarn  lint
